### ISSUE TITLE
使用mysql时报错

### ISSUE THREAD

**Issue by wangyupeng** [yuantiku/flyboard#152]
你好，

我配置的是连接mysql，

进行以下步骤时报错：
npm run migrate:latest

以下是报错信息：

> flyboard@0.0.1 migrate:latest /application/flyboard
> knex --knexfile ./configs/database.js --cwd . migrate:latest

Error: ER_CANT_CREATE_TABLE: Can't create table 'flyboard.#sql-630f_4b' (errno: 150)
    at Query.Sequence._packetToError (/application/flyboard/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/application/flyboard/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/application/flyboard/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/application/flyboard/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/application/flyboard/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/application/flyboard/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
    --------------------
    at Protocol._enqueue (/application/flyboard/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/application/flyboard/node_modules/mysql/lib/Connection.js:201:25)
    at /application/flyboard/node_modules/knex/lib/dialects/mysql/runner.js:42:16
    at tryCatcher (/application/flyboard/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/application/flyboard/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/application/flyboard/node_modules/bluebird/js/main/promise.js:70:37)
    at Runner_MySQL.<anonymous> (/application/flyboard/node_modules/knex/lib/dialects/mysql/runner.js:41:10)
    at Runner_MySQL.tryCatcher (/application/flyboard/node_modules/bluebird/js/main/util.js:26:23)
    at Runner_MySQL._query (/application/flyboard/node_modules/bluebird/js/main/method.js:15:34)
    at Runner_MySQL.<anonymous> (/application/flyboard/node_modules/knex/lib/runner.js:125:15)
    at Runner_MySQL.tryCatcher (/application/flyboard/node_modules/bluebird/js/main/util.js:26:23)
    at Runner_MySQL.query (/application/flyboard/node_modules/bluebird/js/main/method.js:15:34)
    at Runner_MySQL.<anonymous> (/application/flyboard/node_modules/knex/lib/runner.js:134:19)
    at Runner_MySQL.tryCatcher (/application/flyboard/node_modules/bluebird/js/main/util.js:26:23)
    at ReductionPromiseArray._promiseFulfilled (/application/flyboard/node_modules/bluebird/js/main/reduce.js:109:18)
    at Promise._settlePromiseAt (/application/flyboard/node_modules/bluebird/js/main/promise.js:586:26)
    at Promise._settlePromises (/application/flyboard/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/application/flyboard/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/application/flyboard/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/application/flyboard/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)

npm ERR! flyboard@0.0.1 migrate:latest: `knex --knexfile ./configs/database.js --cwd . migrate:latest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flyboard@0.0.1 migrate:latest script.
npm ERR! This is most likely a problem with the flyboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     knex --knexfile ./configs/database.js --cwd . migrate:latest
npm ERR! You can get their info via:
npm ERR!     npm owner ls flyboard
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-573.7.1.el6.x86_64
npm ERR! command "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "run" "migrate:latest"
npm ERR! cwd /application/flyboard
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /application/flyboard/npm-debug.log
npm ERR! not ok code 0

注：连接sqlite3执行正常

**Comment by ChenBooming** [comment]
我也遇到这个问题，请问怎么解决的呢~？
